const listaAtividades = [{
    "id": "0",
    "categoria": "cannoying",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Cannoying no Douro",
    "regiao": "Parque Nacional Peneda-Gerês",
    "dificuldade": "Dificil", 
    "descricao": "Este percurso apresenta uma extensão de cerca de 1000 metros percorridos com recurso a 4 rapeis que variam entre os 6 e 40 metros de altura, caminhada pelo leito do rio, progressão aquática e pequenos saltos para a água. Localizado em pleno Parque Nacional Peneda Gerês, a uma hora e meia de automóvel do Porto, apresenta um fantástico enquadramento natural e paisagístico e grandes lagoas verdes de água límpida. Recomendamos experiência anterior em canyoning ou rapel.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)", 
      "botas de canyoning (Adidas Hydro Lace)", 
      "fato isotérmico de alta performance", 
      "meias de neoprene", 
      "capacete de segurança", 
      "arnês com proteção", 
      "longe dupla", 
      "descensor", 
      "luvas de neoprene (quando necessário)", 
      "sacos de transporte", 
      "bidons estanque", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["2 a 5 participantes - 75€",
      "mais de 5 participantes - 65€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "1",
    "categoria": "canoagem",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Canoagem no Tejo",
    "regiao": "Rio Tejo",
    "dificuldade": "Medio", 
    "descricao": "Este percurso apresenta uma praticada em percursos de 650 e 700 metros. Os canoístas devem passar por 18 a 25 portas, com o menor número de erros possível e num menor espaço de tempo.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)", 
      "Botas de neoprene anti-derrapantes", 
      "Fato isotérmico de neoprene", 
      "Camisola térmico", 
      "Canoa", 
      "Capacete de segurança", 
      "Colete de salvação", 
      "Pá", 
      "Pagaia", 
      "Saiote", 
      "bidons estanque", 
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 25€",
    "mais de 5 participantes - 90€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 20€", 
    "mais de 5 participantes - 80€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "2",
    "categoria": "flyboard",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "3",
    "categoria": "paintball",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Paintball",
    "regiao": "Vila Nova de Gaia",
    "dificuldade": "Facil", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "4",
    "categoria": "passeios tt",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "5",
    "categoria": "rappel",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "6",
    "categoria": "salto de paraquedas",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "7",
    "categoria": "slide",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  },
  {
    "id": "8",
    "categoria": "parapente",
    "imagem": "imgs/canyoning_geres_arado_sup_4.jpg",
    "thumb": "imgs/inicio4.png",
    "nome": "Flyboard",
    "regiao": "Porto",
    "dificuldade": "Medio", 
    "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
    "programa": [
      "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
      "9:30 - Chegada / Ponto de encontro;", 
      "9:40 - Briefing e entrega do equipamento;",
      "10:10 - Início da atividade;",
      "12:30 - Pequena paragem para reforço energético;",
      "16:00 - Final da descida;",
      "16:30 - Snack (opcional);", 
      "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
    "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
      "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
      "seguros em conformidade com a lei (disponível para consulta)",  
      "Capacete de segurança", 
      "colete salva-vidas (quando necessário)",
      "oferta de fotos e vídeos da actividade."],
    "trazer": ["Calção/fato de banho", 
      "Toalha",
      "Snack (ou requerer por 5€ extra)",
      "Água"],
    "preco": ["Preço por pessoa - 80€",
    "mais de 5 participantes - 350€",
    "Preço por pessoa com transporte próprio:",
    "Preço por pessoa - 70€", 
    "mais de 5 participantes - 300€"],
    "extra": "Snack - 5€"
  }
  ]

  export default listaAtividades;