const listaAtividades = [{
  "id": "0",
  "categoria": "cannoying",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Cannoying no Douro",
  "regiao": "Parque Nacional Peneda-Gerês",
  "dificuldade": "Dificil", 
  "descricao": "Este percurso apresenta uma extensão de cerca de 1000 metros percorridos com recurso a 4 rapeis que variam entre os 6 e 40 metros de altura, caminhada pelo leito do rio, progressão aquática e pequenos saltos para a água. Localizado em pleno Parque Nacional Peneda Gerês, a uma hora e meia de automóvel do Porto, apresenta um fantástico enquadramento natural e paisagístico e grandes lagoas verdes de água límpida. Recomendamos experiência anterior em canyoning ou rapel.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Pequena paragem para reforço energético;",
    "16:00 - Final da descida;",
    "16:30 - Snack (opcional);", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)", 
    "botas de canyoning (Adidas Hydro Lace)", 
    "fato isotérmico de alta performance", 
    "meias de neoprene", 
    "capacete de segurança", 
    "arnês com proteção", 
    "longe dupla", 
    "descensor", 
    "luvas de neoprene (quando necessário)", 
    "sacos de transporte", 
    "bidons estanque", 
    "colete salva-vidas (quando necessário)",
    "oferta de fotos e vídeos da actividade."],
  "trazer": ["Calção/fato de banho", 
    "Toalha",
    "Snack (ou requerer por 5€ extra)",
    "Água"],
  "preco": ["Preco por pessoa: 45€"],
  "extra": "Snack - 5€"
},
{
  "id": "1",
  "categoria": "canoagem",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Canoagem no Tejo",
  "regiao": "Rio Tejo",
  "dificuldade": "Medio", 
  "descricao": "Este percurso apresenta uma praticada em percursos de 650 e 700 metros. Os canoístas devem passar por 18 a 25 portas, com o menor número de erros possível e num menor espaço de tempo.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Pequena paragem para reforço energético;",
    "16:00 - Final da descida;",
    "16:30 - Snack (opcional);", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)", 
    "Botas de neoprene anti-derrapantes", 
    "Fato isotérmico de neoprene", 
    "Camisola térmico", 
    "Canoa", 
    "Capacete de segurança", 
    "Colete de salvação", 
    "Pá", 
    "Pagaia", 
    "Saiote", 
    "bidons estanque", 
    "oferta de fotos e vídeos da actividade."],
  "trazer": ["Calção/fato de banho", 
    "Toalha",
    "Snack (ou requerer por 5€ extra)",
    "Água"],
  "preco": ["Preço por pessoa - 25€"],
  "extra": "Snack - 5€"
},
{
  "id": "2",
  "categoria": "flyboard",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Flyboard",
  "regiao": "Porto",
  "dificuldade": "Medio", 
  "descricao": "O Flyboard consiste em ficar parado numa placa (com botas, no qual posiciona os pés) que está conectado a uma mangueira longa, que por sua vez está conectada a um jet ski.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Almoço;",
    "14:30 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)",  
    "Capacete de segurança", 
    "colete salva-vidas (quando necessário)",
    "oferta de fotos e vídeos da actividade."],
  "trazer": ["Calção/fato de banho", 
    "Toalha",
    "Snack (ou requerer por 5€ extra)",
    "Água"],
  "preco": ["Preço por pessoa - 80€"],
  "extra": "Snack - 5€"
},
{
  "id": "3",
  "categoria": "paintball",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Paintball",
  "regiao": "Vila Nova de Gaia",
  "dificuldade": "Facil", 
  "descricao": "O Paintball é jogado ao ar livre, em campos de floresta ou urbanos, nos quais se desenvolve o espírito de equipa, a responsabilidade individual, a liderança e a tomada de decisões sob pressão, exigindo reações rápidas e pensamentos estratégicos.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Pequena paragem para reforço energético;",
    "16:00 - Continuação da atividade;",
    "16:30 - Snack (opcional);", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)", 
    "100 bolas", 
    "Casaco e máscara ",
    "oferta de fotos e vídeos da actividade."],
  "preco": ["Preço por pessoa - 18€"],
  "extra": "Snack - 5€"
},
{
  "id": "4",
  "categoria": "passeios tt",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Passeios TT",
  "regiao": "Douro Superior e Trás-os-Montes",
  "dificuldade": "Medio", 
  "descricao": "O percurso é marcado por trilhos fantásticos para quem procura desfrutar paisagens únicas entre Douro Superior e Trás-os-Montes, com alternativas de troços mais difíceis para os mais audazes.",
  "programa": [
    "08:30 - Abertura do secretariado e pequeno-almoço",
    "09:00 - Início do Passeio",
    "10:30 - Porto de Honra\ hidratação",
    "12:00 - reforço",
    "15:00 - Porto de Honra\ hidratação",
    "16:00 - Almoço",
    "​17:00 - Pista de Obstáculos", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)",  
    "Capacete de segurança", 
    "colete salva-vidas (quando necessário)",
    "oferta de fotos e vídeos da actividade."],
  "preco": ["Preço por pessoa - 30€"],
  "extra": "Snack - 5€"
},
{
  "id": "5",
  "categoria": "rappel",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Rappel",
  "regiao": "Douro",
  "dificuldade": "Dificil", 
  "descricao": "Uma atividade vertical utilizada para descer de lugares altos com o auxílio de uma corda!",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Pequena paragem para reforço energético;",
    "16:00 - Final da descida;",
    "16:30 - Snack (opcional);", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)",  
    "Mosquetões",
    "Cordas",
    "Luvas",
    "Capacete",
    "Freio",
    "Cadeirinha, arnez ou baudrier",
    "oferta de fotos e vídeos da actividade."],
  "preco": ["Preço por pessoa - 40€"],
  "extra": "Snack - 5€"
},
{
  "id": "6",
  "categoria": "salto de paraquedas",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Salto de Paraquedas",
  "regiao": "Douro",
  "dificuldade": "Dificil", 
  "descricao": "Salto tandem realizado a 3000 metros de altitude com queda livre de aproximadamente 25 segundos.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Almoço;",
    "14:30 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "seguros em conformidade com a lei (disponível para consulta)",  
    "Salto com Instrutor a 3000 metros",
    "Todo o equipamento necessário para Salto",
    "Seguro Desportivo",
    "oferta de fotos e vídeos da actividade."],
  "trazer": ["Calção/fato de banho", 
    "Toalha",
    "Snack (ou requerer por 5€ extra)",
    "Água"],
  "preco": ["Preço por pessoa - 160€"],
  "extra": "Snack - 5€"
},
{
  "id": "7",
  "categoria": "slide",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Slide",
  "regiao": "Gerês",
  "dificuldade": "Facil", 
  "descricao": "O slide é um desporto aventura que consiste numa descida rápida, onde o praticante desliza por um cabo de aço esticado com algum declive, utilizando como suporte algum equipamento de escalada.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Almoço;",
    "14:30 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "Enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "Seguros em conformidade com a lei (disponível para consulta)",  
    "Capacete de segurança", 
    "Equipamento necessario",
    "Oferta de fotos e vídeos da actividade."],
  "preco": ["Preço por pessoa - 8€"],
  "extra": "Snack - 5€"
},
{
  "id": "8",
  "categoria": "parapente",
  "imagem": "/imgs/canyoning_geres_arado_sup_4.jpg",
  "thumb": "/imgs/inicio4.png",
  "nome": "Parapente",
  "regiao": "Douro Litoral, Minho e Trás os Montes.",
  "dificuldade": "Dificil", 
  "descricao": "Voar de Parapente é uma experiência única e aquilo que mais gostamos de fazer. Voar e proporcionar aos outros uma experiência pedagógica. O parapente é sem dúvida a forma mais simples que o homem tem para voar e realizar o seu sonho mais antigo. Promovemos actividades ligadas á prática do parapente tanto para pilotos como para pessoas interessadas em experimentar o voo de parapente e quem sabe tornar-se piloto.",
  "programa": [
    "8:00 - Pick up no local de alojamento (no caso de requerer transporte)", 
    "9:30 - Chegada / Ponto de encontro;", 
    "9:40 - Briefing e entrega do equipamento;",
    "10:10 - Início da atividade;",
    "12:30 - Pequena paragem para reforço energético;",
    "16:00 - Continuação da atividade;",
    "16:30 - Snack (opcional);", 
    "18:10 - Drop off no local de alojamento (no caso de requerer transporte)."],
  "inclui": ["Transporte (quando solicitado) a partir do Grande Porto, Braga e Gerês,", 
    "Enquadramento técnico e acompanhamento permanente de monitores altamente qualificados", 
    "Seguros em conformidade com a lei (disponível para consulta)",  
    "Capacete de segurança", 
    "Equipamento necessario para voar",
    "Oferta de fotos e vídeos da actividade."],
  "preco": ["Preço por pessoa - 80€"],
  "extra": "Snack - 5€"
}
]

  export default listaAtividades;